server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.10.103:12345/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: sfy1314
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
missyou:
  security:
    jwt-key: XmchxCoder
    token-expired-in: 86400000
  order:
    max-sku-limit: 77
    pay-time-limit: 1800
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify